using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASPModule.Infrastructure.disruptingLifeCycle
{
    public class InfoHandler : IHttpHandler
    {
        public bool IsReusable => false;

        public void ProcessRequest(HttpContext context)
        {
            if (context.Request.RawUrl == "/Disrupt/ShowData" && DateTime.Now.Second%5 ==0)
            {
                context.Server.TransferRequest("/Home/Index");
            }
            context.Response.Write("Content generated by InfoHandler for test purpose");
            context.Response.Write(string.Format("Time: {0}", DateTime.Now.ToShortTimeString()));
        }
    }
}